apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-job-manager
  labels:
    app: k8s-job-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: k8s-job-manager
  template:
    metadata:
      labels:
        app: k8s-job-manager
    spec:
      containers:
      - name: k8s-job-manager
        image: 52north/pygeoapi-k8s-manager:local
        imagePullPolicy: IfNotPresent
        env:
        - name: PYGEOAPI_K8S_MANAGER_NAMESPACE
          value: default
        - name: PYGEOAPI_K8S_MANAGER_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: k8s-job-manager
              key: token
          #
          # configure log finalizer
          #
#        - name: PYGEOAPI_K8S_MANAGER_FINALIZER_BUCKET_ENDPOINT
#          value: https://obs.eu-de.otc.t-systems.com
#        - name: PYGEOAPI_K8S_MANAGER_FINALIZER_BUCKET_KEY
#          valueFrom:
#            secretKeyRef:
#              name: k8s-job-manager-log-finalizer-credentials
#              key: key
#        - name: PYGEOAPI_K8S_MANAGER_FINALIZER_BUCKET_SECRET
#          valueFrom:
#            secretKeyRef:
#              name: k8s-job-manager-log-finalizer-credentials
#              key: secret
#        - name: PYGEOAPI_K8S_MANAGER_FINALIZER_BUCKET_PATH_PREFIX
#          value: k8s-manager/logs/
          #
          # end of log finalizer
          #
          # pyGeoAPI
          # the config, that defines the ingest API set-up
        - name: PYGEOAPI_CONFIG
          value: "/pygeoapi/local.config.yml"
          # gunicorn
        - name: CONTAINER_NAME
          value: "k8s-job-manager"
        - name: CONTAINER_PORT
          value: "80"
          # ingest
          # Keep in sync with ingress!
        - name: SCRIPT_NAME
          value: "/pygeoapi/"
        - name: WSGI_WORKERS
          value: "4"
        - name: WSGI_WORKER_TIMEOUT
          value: "6000"
        - name: WSGI_WORKER_CLASS
          value: "gevent"
        resources:
          # adjust asap to your set-up
          requests:
            memory: "512M"
            cpu: "100m"
          limits:
            memory: "768M"
            cpu: "250m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /pygeoapi/local.config.yml
          subPath: local.config.yml
      volumes:
      - name: config
        configMap:
          name: k8s-job-manager-config
      restartPolicy: Always
      serviceAccountName: k8s-job-manager
