name: "lint after push"
concurrency:
  group: "pygeoapi-k8s-manager-flake8"
  cancel-in-progress: true
on:
  [ push, pull_request ]
jobs:
  flake8:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v4
      -
        name: install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install -r requirements-dev.txt
      -
        name: run flake8
        run: |
          flake8 pygeoapi_kubernetes_manager
          flake8 tests
