name: "lint and test after push"
concurrency:
  group: "pygeoapi-k8s-manager-push-lint-and-test"
  cancel-in-progress: true
on:
  # all pushes and PRs, but not tags
  push:
    branches:
      - '**'
  pull_request:
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v4
      -
        name: install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install -r requirements-dev.txt
      -
        name: run linter and formatter
        run: |
          ruff check
          ruff check --select I
          ruff format --diff
      -
        name: run tests
        run: |
          pytest tests/
