name: "lint after push"
concurrency:
  group: "pygeoapi-k8s-manager-push-lint"
  cancel-in-progress: true
on:
  [ push, pull_request ]
jobs:
  linter:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v4
      -
        name: install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install -r requirements-dev.txt
      -
        name: run linter
        run: |
          ruff check
          ruff format --diff
